### ISSUE TITLE
Different Errors

### ISSUE THREAD

**Issue by BlackSeBo** [maektwain/cryptonote-wallet#1]
Hi,

I used a few different methods but like using it on Windows or on Linux or now inside an Docker Container under plesk but still have the same problem everytime. I am a bit stupid sometimes and maybe it is something really easy to fix and normally I am able to fix my problems somehow but not this time.

It starts with the Command “yarn install”

There I get a warning I am not sure what to do about it and to be honest I ignored it because at the end it looked like it is ok with that
________________________________________
warning " > bootstrap@4.0.0-beta.2" has unmet peer dependency "popper.js@^1.12.3".
________________________________________

The second and main problem appears when I execute the command “./mvnw” there I get 3 errors

This is the Debug output when I execute “./mvnw –X”

________________________________________
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/jhipster/app/src/main/java/com/talentum/wallet/web/rest/AccountResource.java:[83,17] unclosed character literal
[ERROR] /home/jhipster/app/src/main/java/com/talentum/wallet/web/rest/AccountResource.java:[83,28] unclosed character literal
[ERROR] /home/jhipster/app/src/main/java/com/talentum/wallet/web/rest/AccountResource.java:[86,81] ';' expected
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.960 s
[INFO] Finished at: 2018-02-20T13:41:38Z
[INFO] Final Memory: 31M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project wallet: Compilation failure: Compilation failure:
[ERROR] /home/jhipster/app/src/main/java/com/talentum/wallet/web/rest/AccountResource.java:[83,17] unclosed character literal
[ERROR] /home/jhipster/app/src/main/java/com/talentum/wallet/web/rest/AccountResource.java:[83,28] unclosed character literal
[ERROR] /home/jhipster/app/src/main/java/com/talentum/wallet/web/rest/AccountResource.java:[86,81] ';' expected
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project wallet: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:353)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1161)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 31 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

________________________________________

It is not like I didn’t tried to fix them by myself but every time I fix one problem another one appears. 

I am still a newbie in Coding stuff my experience is only one 1 year of easiest Web development  a little bit of Android Development so I am still learning this stuff.

I hope you can help me and I am very sorry to bother you with that and for my bad English.

**Comment by maektwain** [comment]
Now try I had some unfinished code.

Let me know if that works just clone the repo again or pull the changes.

Thanks

**Comment by BlackSeBo** [comment]
Thanks for the reply and for your help now everything is working well.
I can access the websites over localhost:3000 localhost:8080 and localhost:9000 but i am not sure maybe i misunderstood something with the repository name but when you say "Cryptonote Web Wallet" do you meen something like this 

https://bytecoin.money/#/login

or something diffrent because i can not find any content it look like the basic template page of jhippster where it says welcome to jhippster

**Comment by maektwain** [comment]
Yeah , I am still working on the codes , I have not finished working on it . Sorry you cloned too early.

Let me know if you would like to help me in the coding. thanks
